## 50 câu hỏi ngắn về Numpy

### Câu hỏi 1: import numpy dưới bí danh np và xem phiên bản

In [1]:
import numpy as np
print( np.__version__)

2.0.2


### Câu hỏi 2: Làm thế nào để tạo mảng 1 chiều?

In [5]:
import numpy as np
array1 = np.array( [0, 1, 2, 3, 4, 5] )
array2 = np.arange( 0, 10, 1 )
print( array1 )
print( array2 )

[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


### Câu hỏi 3: Làm thế nào để tạo một mảng boolean?

In [14]:
array1 = np.ones( 10, dtype = bool )
print( array1 )

[ True  True  True  True  True  True  True  True  True  True]


In [17]:
array2 = np.ones( 10, dtype = bool ).reshape(2, 5)
print( array2 )

[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [16]:
array3 = np.array( [1, 2, 4, 6, 5, 11, 15, 4 ] )
array3 = array3 % 2 == 0
print( array3 )

[False  True  True  True False False False  True]


In [18]:
array3 = np.array( [True, False, True, True, True, False ] )
print ( array3 )

[ True False  True  True  True False]


### Câu hỏi 4: Làm thế nào để trích xuất các mục thỏa mãn một điều kiện nhất định từ mảng 1 chiều?
Ví dụ: Trích xuất tất cả các số lẻ từ mảng

In [19]:
import numpy as np 
array1 = np.arange( 0, 10, 1 ) 
sole = array1[ array1 % 2 != 0 ]
print( sole )

[1 3 5 7 9]


### Câu hỏi 5: Làm thế nào để thay thế các mục thỏa mãn một điều kiện bằng một giá trị khác trong mảng numpy?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1

In [14]:
import numpy as np 
arr = np.arange( 0, 10, 1 ) 
arr[ arr % 2 != 0 ] = -1
print( arr )

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Câu hỏi 6: Làm thế nào để thay thế các mục thỏa mãn một điều kiện mà không ảnh hưởng đến mảng ban đầu?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1 mà không thay đổi arr

In [12]:
import numpy as np
arr = np.arange(0, 10, 1 )
arr_copy = arr.copy()
arr_copy[ arr_copy % 2 != 0 ] = -1
print( arr, arr_copy)

[0 1 2 3 4 5 6 7 8 9] [ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Câu hỏi 7: Làm thế nào để định hình lại một mảng?

In [11]:
import numpy as np
arr = np.arange(0, 10, 1 )
arr = arr.reshape( 2, 5 )
print( arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Câu hỏi 8: Làm thế nào để xếp chồng hai mảng theo chiều dọc?

In [23]:
import numpy as np
arr1 = np.arange(0, 10, 1 )
arr2 = np.arange(10, 20, 1)
arr3 = np.vstack( (arr1, arr2) )
print ( arr3 )

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


### Câu hỏi 9: Làm thế nào để xếp chồng hai mảng theo chiều ngang?

In [22]:
import numpy as np
arr1 = np.arange( 0, 10, 1 )
arr2 = np.arange( 10, 20, 1)
arr3 = np.hstack( (arr1, arr2) )
print( arr3 )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### Câu hỏi 10: Làm thế nào để tạo các chuỗi tùy chỉnh trong numpy mà không cần mã hóa cứng?
Ví dụ: 
Input: a = np.array([1,2,3])

Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
import numpy as np
a = np.array( [1,2,3] )
output1 = np.repeat(a, 3)

output2 = np.tile( a, (3,1) )
output2 = output2.flatten()

output = np.hstack( (output1, output2 ) )
print( output )

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### Câu hỏi 11. Làm thế nào để lấy các mục chung giữa hai mảng numpy python?
Ví dụ: 
Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

        b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: array([2, 4])

In [24]:
import numpy as np
a = np.array( [ 1, 2, 3, 2, 3, 4, 3 ,4, 5, 6 ] )
b = np.array( [7, 2, 10, 2, 7, 4, 9, 4, 9, 8 ] )

output = np.intersect1d( a, b )
print( output )

[2 4]


### Câu hỏi 12. Làm thế nào để xóa khỏi một mảng những mục tồn tại trong mảng khác? 
Ví dụ: Input: a = np.array([1,2,3,4,5])

              b = np.array([5,6,7,8,9])

Output: array([1,2,3,4])

In [26]:
import numpy as np
a = np.array( [ 1, 2, 3, 4, 5 ] )
b = np.array( [ 5, 6, 7, 8, 9 ] )

output = np.setdiff1d( a, b )
print ( output )

[1 2 3 4]


### Câu hỏi 13. Làm thế nào để lấy các vị trí mà các phần tử của hai mảng khớp nhau?

Ví dụ: 

Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

       b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: (array([1, 3, 5, 7]),)

In [28]:
import numpy as np
a = np.array( [1, 2, 3, 2, 3, 4, 3, 4, 5, 6 ] )
b = np.array( [7, 2, 10, 2, 7, 4, 9, 4, 9 ,8] )

vitrikhop = np.where( a == b )
print ( vitrikhop )

(array([1, 3, 5, 7]),)


### Câu hỏi 14. Làm thế nào để trích xuất tất cả các số trong một phạm vi nhất định từ một mảng numpy?

Ví dụ: 
Input: a = np.array([2, 6, 1, 9, 10, 3, 27])

Output: (array([6, 9, 10]),)

In [30]:
import numpy as np

a = np.array( [2, 6, 1, 9, 10, 3, 27 ] )
output = a[ ( a >=6 ) & ( a <=10 ) ]
print( output )



[ 6  9 10]


### Câu hỏi 16. Làm thế nào để hoán đổi hai cột trong một mảng numpy 2 chiều? 

In [27]:
import numpy as np
a = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
a[:, [0,2] ] = a[:, [2,0] ]
print(a )

[[3 2 1]
 [6 5 4]
 [9 8 7]]


### Câu hỏi 17. Làm thế nào để hoán đổi hai hàng trong một mảng numpy 2 chiều? 

In [31]:
import numpy as np
a = np.array ( [ [1,2,3], [4,5,6], [7,8,9] ] )
a[ [0, 2 ] ] = a[ [2, 0 ] ]
print( a )

[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Câu hỏi 18. Làm thế nào để đảo ngược các hàng của một mảng 2 chiều? 

In [34]:
import numpy as np
a = np.array( [ [1,2,3], [4,5,6] , [7,8,9] ] )
a = a[::-1]
print ( a )


[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Câu hỏi 19. Làm thế nào để đảo ngược các cột của một mảng 2 chiều?

In [37]:
import numpy as np
a = np.array( [ [1,2,3], [4,5,6] , [7,8,9] ] )
a = a[:, ::-1 ]
print(a)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


### Câu hỏi 20. Làm thế nào để tạo một mảng 2 chiều chứa các số thực ngẫu nhiên giữa 5 và 10?

In [40]:
import numpy as np
a = np.random.uniform( 5, 10, size = (3, 4 ) )
print( a )

[[5.17468158 9.93561492 7.60958945 9.72558555]
 [6.53786148 5.45020016 9.68350071 6.1984197 ]
 [5.62797697 6.14906792 7.55923906 8.83492663]]


### Câu hỏi 21. Làm thế nào để chỉ in 3 chữ số thập phân trong mảng numpy python? 

In [44]:
import numpy as np
import math as m
a = np.random.uniform( 0, 5 , size = 10) 
print( np.round ( a, 3 ) )

[3.382 2.393 1.912 3.507 2.745 1.476 1.955 3.363 4.815 4.087]


### Câu hỏi 22. Làm thế nào để in đẹp một mảng numpy bằng cách loại bỏ ký hiệu khoa học (như 1e10)? 

In [56]:
import numpy as np
a = np.array( [ 1e10, 1.23e5, 3.45e8, 2.34e2] )
print( a )
np.set_printoptions(suppress = True, formatter = {'float_kind':'{:f}'.format})
print( a )

[1.00000000e+10 1.23000000e+05 3.45000000e+08 2.34000000e+02]
[10000000000.000000 123000.000000 345000000.000000 234.000000]


### Câu hỏi 24. Làm thế nào để in toàn bộ mảng numpy mà không cần cắt bớt

In [69]:
import numpy as np
a = np.arange( 1000 )
np.set_printoptions( threshold = np.inf )
print ( a) 

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

### Câu hỏi 28. Làm thế nào để tính giá trị trung bình, trung vị, độ lệch chuẩn của một mảng numpy?

In [71]:
import numpy as np
a = np.array( [1, 2, 3, 2, 3, 4, 3, 4, 5, 6 ] )
trungbinh = np.mean( a )
trungvi = np.median( a )
dolechchuan = np.std( a )

print ( trungbinh , '   ' , trungvi, '   ', dolechchuan )

3.3     3.0     1.4177446878757827


### Câu hỏi 29. Làm thế nào để chuẩn hóa một mảng sao cho các giá trị nằm chính xác trong khoảng từ 0 đến 1?

In [84]:
import numpy as np
arr = np.array( [ 10, 20, 30, 40, 50] )

arr_min = arr.min()
arr_max = arr.max()

chuanhoa = ( arr - arr_min )/( arr_max - arr_min)
print(a )

[80 59 22 12 23 20  4 58  6 23]


### Câu hỏi 30. Làm thế nào để tính điểm softmax?

In [85]:
import numpy as np
arr = np.random.uniform( 1, 10, 5 )

def softmax(x):
    e_mu_x = np.exp( x- np.max( x ) )

    soft_max = e_mu_x / np.sum( e_mu_x )
    return soft_max

ketqua = softmax( arr )
print( ketqua )

[0.00266727 0.07008594 0.00168232 0.54522067 0.38034379]


### Câu hỏi 32. Làm thế nào để chèn các giá trị ở các vị trí ngẫu nhiên trong một mảng?

Ví dụ: Chèn giá trị 0 vào 20 vị trí ngẫu nhiên trong tập dữ liệu a

In [96]:
import numpy as np
arr = np.random.randint( 1, 100, (30))

soluongchen = 20

chi_so_chen = np.random.choice( arr.size, soluongchen, replace = False )

arr_new = np.insert( arr, chi_so_chen, 0 )

print ( arr_new )

[ 0 13  0 28 92  9  0  3 38  0 86  0 24  0 81  0  3  0 96  8  0  2  0 32
  0  9  0 74 52  0 78  0 58 30  0 49  0 69 97 18  0 84 52  0 22 77  0 22
  0 13]


### Câu hỏi 34. Làm thế nào để lọc một mảng numpy dựa trên hai hoặc nhiều điều kiện?

Ví dụ: Lọc các hàng của a có các giá trị của (cột thứ 3) > 1,5 và các giá trị (cột thứ 1) < 5,0

In [112]:
import numpy as np
arr = np.random.uniform( 0.0, 20.0 , (5, 3))

arr_new = ( arr[ :, 2 ] > 1.5 ) & ( arr[:, 0 ] < 5.0 ) 

arr_filtered = arr[ arr_new ]
print( arr_filtered) 

[[ 3.00416891 11.72243150  9.35249907]
 [ 0.53302083  5.56993270 13.94109225]]


### Câu hỏi 36. Làm thế nào để tìm mối tương quan giữa hai cột của mảng numpy?

In [119]:
import numpy as np
arr = np.random.randint( 0, 20 , (5, 3))

col1 = arr[: , 0 ]
col2 = arr[: , 1 ]

moituongquan = np.corrcoef( col1, col2 )
print(moituongquan)

[[1.00000000 0.40487438]
 [0.40487438 1.00000000]]


### Câu hỏi 44. Làm thế nào để sắp xếp một mảng 2D theo một cột

In [125]:
import numpy as np
arr = np.random.randint( 0, 20, ( 5, 3) )
#sắp xếp theo cột thứ 2
sorted_arr = arr[ arr[ :, 1 ].argsort() ]

print(arr )
print()
print( sorted_arr )

[[14 18 17]
 [ 7 12  1]
 [ 1 16 19]
 [ 9 16  8]
 [15 14 13]]

[[ 7 12  1]
 [15 14 13]
 [ 1 16 19]
 [ 9 16  8]
 [14 18 17]]


### Câu hỏi 45. Làm thế nào để tìm giá trị thường xuyên nhất trong một mảng numpy?

In [129]:
import numpy as np
arr = np.array( [1, 2, 2, 3, 4, 2, 5, 3, 4, 4, 4] )
#giá trị duy nhất và số lần xuất hiện 
duynhat, solan = np.unique( arr, return_counts = True )

solan_xuathien_max = np.argmax(solan)

giatrithuongxuyen_max = duynhat[solan_xuathien_max ] 

print( duynhat)

print( giatrithuongxuyen_max )


[1 2 3 4 5]
4


### Câu hỏi 47. Làm thế nào để thay thế tất cả các giá trị lớn hơn một giá trị nhất định thành một ngưỡng nhất định?

Ví dụ: Từ mảng a, thay thế tất cả các giá trị lớn hơn 30 đến 30 và nhỏ hơn 10 đến 10.

In [130]:
import numpy as np
arr = np.array( [5, 12, 45, 7, 25, 32, 9] )

#giá trị nhỏ hơn 10 sẽ thành 10, giá trị lớn hơn 30 sẽ thành 30 
arr_clipped = np.clip( a, 10, 30 )

print(arr )
print( arr_clipped )

[ 5 12 45  7 25 32  9]
[30 30 22 12 23 20 10 30 10 23]


### Câu hỏi 48. Làm thế nào để lấy vị trí của n giá trị hàng đầu từ một mảng numpy?

Ví dụ: Lấy vị trí của 5 giá trị lớn nhất trong một mảng cho trước a.

In [133]:
import numpy as np
arr = np.random.randint( 0, 100, 10 )

n = 5
n_giatrimax = np.argpartition(arr, -n)[-n:]

print( arr )
print( 'vi tri 5 gia tri lon nhat : ' , n_giatrimax )


[ 2 89 21 76  9 42 21 93 93 27]
vi tri 5 gia tri lon nhat :  [5 3 1 8 7]


### Câu hỏi 50. Làm thế nào để chuyển đổi một mảng các mảng thành một mảng phẳng 1 chiều?

In [ ]:
import numpy as np
arr = np.random.randint( 0, 100, (5,4) )
print( arr )